package planservices

type PlanServices struct {
	Name      string `json:"name"`
	Id        string `json:"id"`
	Created   string `json:"created"`
	Updated   string `json:"updated"`
	Endpoints []struct {
		Name    string `json:"name"`
		Methods []struct {
			Name string `json:"name"`
			Id   string `json:"id"`
		} `json:"methods"`
		Id string `json:"id"`
	} `json:"endpoints"`
}

type AutoGenerated struct {
	Services []struct {
		ID        string `json:"id"`
		Name      string `json:"name"`
		Created   string `json:"created"`
		Updated   string `json:"updated"`
		Endpoints []struct {
			ID      string `json:"id"`
			Created string `json:"created"`
			Updated string `json:"updated"`
			Name    string `json:"name"`
			Methods []struct {
				ID               string      `json:"id"`
				Created          string      `json:"created"`
				Updated          string      `json:"updated"`
				Name             string      `json:"name"`
				ResponseFilter   interface{} `json:"responseFilter"`
				RateLimitCeiling int         `json:"rateLimitCeiling"`
				RateLimitExempt  bool        `json:"rateLimitExempt"`
				RateLimitPeriod  string      `json:"rateLimitPeriod"`
				QPSLimitCeiling  int         `json:"qpsLimitCeiling"`
				QPSLimitExempt   bool        `json:"qpsLimitExempt"`
			} `json:"methods"`
			UndefinedMethodsAllowed bool `json:"undefinedMethodsAllowed"`
		} `json:"endpoints"`
	} `json:"services"`
}

type DeletePlanResponse struct {
	Status string `json:"status"`
}

type MethodParams struct {
	PackageId string
	PlanId    string
	ServiceId string
}
